name: Build AAPS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      
      - name: Decode and Rename Keystore
        run: |
          echo "${{ secrets.STORE_FILE }}" | tr -d '\n' | base64 -d > aaps.keystore
          mkdir -p keystore
          cp aaps.keystore keystore/demokeystore.jks
          ls -la keystore/demokeystore.jks

      - name: Debug - Check keystore
        run: |
          echo "${{ secrets.STORE_FILE }}" | tr -d '\n' | base64 -d > keystore/demokeystore.jks
          ls -la keystore/demokeystore.jks
          file keystore/demokeystore.jks
          keytool -list -keystore keystore/demokeystore.jks -storepass "123456" || echo "❌ 密码或文件错误！"

      - name: Build Full Release
        run: |
          chmod +x gradlew
          ./gradlew assembleFullRelease \
            -Pandroid.injected.signing.store.file=keystore/demokeystore.jks \
            -Pandroid.injected.signing.store.password="${{ secrets.STORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: aaps-release-apk
          path: app/build/outputs/apk/full/release/*.apk
          if-no-files-found: error
