name: Build AAPS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.STORE_FILE }}" | tr -d '\n' | base64 -d > app/aaps.keystore
          ls -la app/aaps.keystore
          file app/aaps.keystore

      - name: Build Release APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=app/aaps.keystore \
            -Pandroid.injected.signing.store.password="${{ secrets.STORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: aaps-release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
