name: Build AAPS
on: [workflow_dispatch] # 手动触发
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Setup JDK
uses: actions/setup-java@v3
with:
distribution: 'test'
java-version: '11'
- name: Decode Keystore
run: |
echo "${{ secrets.STORE_FILE }}" > keystore_base64.txt
base64 -d keystore_base64.txt > app/aaps.keystore
- name: Build APK
run: |
chmod +x gradlew
./gradlew assembleRelease
-PstorePassword=${{ secrets.STORE_PASSWORD }}
-PkeyPassword=${{ secrets.KEY_PASSWORD }}
-PkeyAlias=${{ secrets.KEY_ALIAS }}
- uses: actions/upload-artifact@v3
with:
name: aaps-release
path: app/build/outputs/apk/release/*.apk
